sudo: required

language: php
services:
    - docker

env:
    global:
        - DOCKER_ORGANIZATION=juliendufresne
    #        - DOCKER_COMPOSE_VERSION=1.22.0
    matrix:
        - DOCKER_IMAGE=php DOCKER_IMAGE_TAG=7.1
        - DOCKER_IMAGE=php DOCKER_IMAGE_TAG=7.2
#        - DOCKER_IMAGE=php-parallel-lint DOCKER_IMAGE_TAG=1.0

before_install:
    - docker rmi $(docker images -q $DOCKER_ORGANIZATION/$DOCKER_IMAGE) || true
    - docker pull $DOCKER_ORGANIZATION/$DOCKER_IMAGE:$DOCKER_IMAGE_TAG || true
#  - sudo rm /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin

script:
    - docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) --build-arg VERSION=$DOCKER_IMAGE_TAG --tag $DOCKER_ORGANIZATION/$DOCKER_IMAGE:$DOCKER_IMAGE_TAG --cache-from $DOCKER_ORGANIZATION/$DOCKER_IMAGE $DOCKER_IMAGE

after_success:
    - |
        if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u "$DOCKER_HUB_LOGIN" -p "$DOCKER_HUB_PASSWORD"
            docker push $DOCKER_ORGANIZATION/$DOCKER_IMAGE:$DOCKER_IMAGE_TAG
        fi

notifications:
    email:
        on_failure: change
        on_success: never
