sudo: required

language: bash

git:
    depth: 3
    quiet: true

services:
  - docker

env:
    global:
      - DOCKER_ORGANIZATION=juliendufresne LATEST=false
    matrix:
       - IMAGE=php               TAG=7.1
       - IMAGE=php               TAG=7.2  LATEST=true
       - IMAGE=php-cs-fixer      TAG=2.13 PHP_VERSION=7.1
       - IMAGE=php-cs-fixer      TAG=2.13 PHP_VERSION=7.2 LATEST=true
       - IMAGE=php-parallel-lint TAG=1.0  PHP_VERSION=7.1
       - IMAGE=php-parallel-lint TAG=1.0  PHP_VERSION=7.2 LATEST=true
       - IMAGE=phpmetrics        TAG=2.3  PHP_VERSION=7.1
       - IMAGE=phpmetrics        TAG=2.3  PHP_VERSION=7.2 LATEST=true
       - IMAGE=phpstan           TAG=0.10 PHP_VERSION=7.1
       - IMAGE=phpstan           TAG=0.10 PHP_VERSION=7.2 LATEST=true
       - IMAGE=speccy            TAG=0.7  LATEST=true
       - IMAGE=textlint          TAG=11.0 LATEST=true

install:
  - sudo docker pull $DOCKER_ORGANIZATION/$IMAGE:$TAG || true

script:
  - ./test.sh $DOCKER_ORGANIZATION $IMAGE $TAG

after_success:
  - |
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
          echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_LOGIN" --password-stdin
          if $LATEST; then
              docker tag $DOCKER_ORGANIZATION/$IMAGE:$TAG $DOCKER_ORGANIZATION/$IMAGE:latest
          fi
          docker push $DOCKER_ORGANIZATION/$IMAGE
      fi

notifications:
    email:
        on_failure: change
        on_success: never
