sudo: required

language: bash

git:
    depth: 3
    quiet: true

services:
  - docker

env:
    global:
      - DOCKER_ORGANIZATION=juliendufresne
    matrix:
       - DOCKER_IMAGE=php               DOCKER_IMAGE_TAG=7.1
       - DOCKER_IMAGE=php               DOCKER_IMAGE_TAG=7.2
       - DOCKER_IMAGE=php-cs-fixer      DOCKER_IMAGE_TAG=2.13
       - DOCKER_IMAGE=php-parallel-lint DOCKER_IMAGE_TAG=1.0
       - DOCKER_IMAGE=phpmetrics        DOCKER_IMAGE_TAG=2.3

install:
  - sudo docker pull $DOCKER_ORGANIZATION/$DOCKER_IMAGE:$DOCKER_IMAGE_TAG || true
  - sudo docker pull composer:latest || true

script:
  - ./test.sh $DOCKER_ORGANIZATION $DOCKER_IMAGE $DOCKER_IMAGE_TAG

after_success:
  - |
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
          echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_LOGIN" --password-stdin
          docker push $DOCKER_ORGANIZATION/$DOCKER_IMAGE
      fi

notifications:
    email:
        on_failure: change
        on_success: never
